{% set version="1.11.1" %}
{% set name="msPurity" %}
{% set bioc="3.8" %}

package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'

source:
  url: https://github.com/computational-metabolomics/msPurity/archive/20f144a3c393bedb0c87e2cd1eed4b8e10428e41.zip


build:
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - libgfortran
    - libnetcdf
    - r-base
    - 'bioconductor-xcms=3.4.4'
    - 'bioconductor-camera=1.38.1'
    - bioconductor-mspuritydata
    - bioconductor-keggrest
    - r-optparse
    - r-dbi
    - r-dosnow
    - r-fastcluster
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-dplyr
    - r-dbplyr
    - r-rcpp
    - r-reshape2
    - r-rsqlite
    - r-stringr
    - r-uuid
    - r-jsonlite


  run:
    - libgfortran
    - libnetcdf
    - r-base
    - 'bioconductor-xcms=3.4.4'
    - 'bioconductor-camera=1.38.1'
    - bioconductor-mspuritydata
    - bioconductor-keggrest
    - r-optparse
    - r-dbi
    - r-dosnow
    - r-fastcluster
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-dplyr
    - r-dbplyr
    - r-rcpp
    - r-reshape2
    - r-rsqlite
    - r-stringr
    - r-uuid
    - r-jsonlite

  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'');library(dbplyr);"'

about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
  summary: 'Assess the contribution of the targeted precursor in fragmentation acquired or anticipated isolation windows using a metric called "precursor purity". Also provides simple processing steps (averaging, filtering, blank subtraction, etc) for DI-MS data. Works for both LC-MS(/MS) and DI-MS(/MS) data. Spectral matching of fragmentation spectra can also be run against a SQLite database of library spectra.'

