{% set version="1.9.7" %}
{% set name="msPurity" %}
{% set bioc="3.8" %}


package:
  name: 'bioconductor-{{ name|lower}}'
  version: '{{ version }}'

source:

  fn: msPurity-3ea03aa9ec23076e372c489cca4874256d09a71e.zip
  url: https://github.com/computational-metabolomics/msPurity/archive/3ea03aa9ec23076e372c489cca4874256d09a71e.zip


requirements:
  build:
    - 'libnetcdf 4.4.*'
    - 'r-base >=3.4.1'
    - 'bioconductor-xcms >=3.0.0'
    - 'bioconductor-camera >=1.34.0'
    - bioconductor-mspuritydata
    - r-optparse    
    - r-dbi
    - r-dosnow
    - r-fastcluster
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-rcpp
    - r-reshape2
    - r-rsqlite
    - r-stringr
    - gcc  # [linux]
    - llvm  # [osx]
  run:
    - 'libnetcdf 4.4.*'
    - 'r-base >=3.4.1'
    - 'bioconductor-xcms >=3.0.0'
    - 'bioconductor-camera >=1.34.0'
    - bioconductor-mspuritydata
    - r-optparse    
    - r-dbi
    - r-dosnow
    - r-fastcluster
    - r-foreach
    - r-ggplot2
    - r-plyr
    - r-rcpp
    - r-reshape2
    - r-rsqlite
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>= 2)'
summary: 'Assess the contribution of the targeted precursor in fragmentation acquired or anticipated isolation windows using a metric called "precursor purity". Also provides simple processing steps (averaging, filtering, blank subtraction, etc) for DI-MS data. Works for both LC-MS(/MS) and DI-MS(/MS) data. Spectral matching of fragmentation spectra can also be run against a SQLite database of library spectra.'
